# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c54e138971c32df6b4e7e338c4a1d7399efd2513b8db3684b65f5ae102280b7a4172b527325e8583ca3465064e0be4cbc02eee057f614669a77d37ffe2d0717e

test:
  secret_key_base: c7b2a6d6972dcf54941137fb54c7916fc38771937d5a4b1bde735f8d5175bca2d39fdb591467574c9efd74830f8d4ce8f15eb3e393d90703bc6dedc93ec6fd11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
